name: .NET Core Build & Test

on: [push, pull_request]
jobs:
  build:

    name: Github Actions Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 3.1.100
    - name: Build Reason
      run: echo ${{github.ref}} and ${{github.event_name}}
    - name: Build with dotnet
      run: dotnet build --configuration Release --nologo ./src/Cov19API.sln
    - name: Run tests
      run: dotnet test --configuration Release --no-build --nologo ./src/Cov19API.sln
    - if: github.event_name == 'push' && contains(github.ref, 'tags')
      name: Push to NuGet
      run: |
        dotnet pack --configuration Release --nologo -o nuget ./src/Cov19API.sln
        dotnet nuget push ./nuget/UKCovid*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_PUBLISH_KEY}}
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
