name: .NET Core Release

on: [release]
jobs:
  build:

    name: Github Actions Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_PUBLISH_KEY}}
      - name: Build Reason
        run: echo ${{github.ref}} and ${{github.event_name}}
      - name: dotnet pack
        run: dotnet pack --configuration Release --nologo -o nuget ./src/Cov19API.sln
      - name: dotnet push
        run: dotnet nuget push ./nuget/UKCovid*.nupkg
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
